"""LightDM greeter configuration (§8 lock — silent greeter setup).

Writes /etc/lightdm/lightdm-gtk-greeter.conf via pkexec so the login
screen mirrors the active preset: Orchis-Dark theme, Black-Sun icons,
Red Hat Text, standard wallpaper, default-preset accent color.

Called from `apply_preset` (mackes.presets) after the appearance section
runs. Idempotent: re-running with the same preset produces no diff.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Optional

from mackes.logging import log_action

GREETER_CONF = Path("/etc/lightdm/lightdm-gtk-greeter.conf")
STANDARD_WALLPAPER = Path("/usr/share/mde/branding/standard-wallpaper.png")
# Accent-per-preset, mirrored to greeter via the gtk-theme + a small CSS overlay
GREETER_DROPIN = Path("/etc/lightdm/lightdm.conf.d/50-mackes.conf")


def _have(cmd: str) -> bool:
    return shutil.which(cmd) is not None


def _pkexec_write(path: Path, contents: str) -> tuple[int, str]:
    """Use AdminSession to write a file as root. Returns (rc, stderr).

    v1.4.4: Route through AdminSession so the sudoers NOPASSWD coverage
    on `tee /etc/lightdm/*` fires and the user never sees a prompt.
    The stdin-piped `tee` form needs special handling — AdminSession.run
    doesn't pipe stdin, so we shell out via `bash -c "cat > path"` when
    NOPASSWD is active, or fall back to legacy pkexec-with-stdin.
    """
    try:
        from mackes.admin_session import AdminSession
        sess = AdminSession.instance()
    except Exception:  # noqa: BLE001
        sess = None

    # Fast path — NOPASSWD active: write contents to a tmpfile, then
    # `install -m 0644 tmpfile target` via the cached sudo creds.
    if sess is not None and sess.is_unlocked():
        import tempfile, os as _os
        try:
            fd, tmp = tempfile.mkstemp(prefix="mackes-lightdm.", suffix=".conf")
            with _os.fdopen(fd, "w") as f:
                f.write(contents)
            rc, out = sess.run(
                ["install", "-D", "-m", "0644", tmp, str(path)],
                timeout=10,
            )
            try: _os.unlink(tmp)
            except OSError: pass
            return rc, out
        except OSError as e:
            return 1, str(e)

    # Legacy fallback: stdin-piped pkexec/sudo tee.
    if _have("pkexec"):
        prefix = ["pkexec"]
    elif _have("sudo"):
        prefix = ["sudo"]
    else:
        return 127, "neither pkexec nor sudo available"
    cmd = prefix + ["tee", str(path)]
    try:
        proc = subprocess.run(cmd, input=contents, text=True,
                              capture_output=True, timeout=30)
    except (OSError, subprocess.TimeoutExpired) as e:
        return 1, str(e)
    return proc.returncode, proc.stderr or ""


def _pkexec_mkdir(path: Path) -> tuple[int, str]:
    """v1.4.4 — route through AdminSession."""
    try:
        from mackes.admin_session import AdminSession
        rc, out = AdminSession.instance().run(
            ["mkdir", "-p", str(path)], timeout=10)
        return rc, out
    except Exception:  # noqa: BLE001
        pass
    if _have("pkexec"):
        prefix = ["pkexec"]
    elif _have("sudo"):
        prefix = ["sudo"]
    else:
        return 127, "neither pkexec nor sudo available"
    cmd = prefix + ["mkdir", "-p", str(path)]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.TimeoutExpired) as e:
        return 1, str(e)
    return proc.returncode, proc.stderr or ""


def configure_greeter(
    *,
    gtk_theme: str = "Orchis-Dark",
    icon_theme: str = "Mackes-Carbon",
    font_name: str = "Red Hat Text 11",
    wallpaper: Optional[Path] = None,
    accent_color: str = "#fa4d56",
) -> list[str]:
    """Write the LightDM greeter config. Returns action log."""
    actions: list[str] = []
    wp = wallpaper or STANDARD_WALLPAPER
    # Phase 8.1 of the v1.0.0 work: greeter mirrors mackes-panel's top
    # bar — strip lives at the top, HH:MM clock format, status-only
    # indicators on the right (host/spacer/clock/spacer/session/a11y/
    # power). Visual continuity Plymouth → LightDM → mackes-panel.
    conf = f"""# Generated by Mackes Shell (mackes.lightdm.configure_greeter)
[greeter]
background = {wp}
theme-name = {gtk_theme}
icon-theme-name = {icon_theme}
font-name = {font_name}
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
cursor-theme-name = Adwaita
cursor-theme-size = 24
# Top-bar mirror order: spacer pushes everything right, then
# clock / session / a11y / power cluster matches mackes-panel's
# status cluster on the right.
indicators = ~spacer;~clock;~spacer;~session;~a11y;~power
clock-format = %H:%M
position = 50%,center 50%,center
default-user-image = #avatar-default
# Match mackes-panel's top-bar location so the strip stays in place
# across boot → greeter → desktop.
panel-position = top
"""
    rc, err = _pkexec_write(GREETER_CONF, conf)
    if rc == 0:
        actions.append(f"wrote {GREETER_CONF}")
    else:
        actions.append(f"could not write {GREETER_CONF}: {err.strip()}")

    # Drop-in: ensure lightdm-gtk-greeter is the selected greeter
    dropin = "[Seat:*]\ngreeter-session=lightdm-gtk-greeter\n"
    rc2, err2 = _pkexec_mkdir(GREETER_DROPIN.parent)
    if rc2 == 0:
        rc3, err3 = _pkexec_write(GREETER_DROPIN, dropin)
        if rc3 == 0:
            actions.append(f"wrote {GREETER_DROPIN}")
        else:
            actions.append(f"could not write {GREETER_DROPIN}: {err3.strip()}")
    else:
        actions.append(f"could not create {GREETER_DROPIN.parent}: {err2.strip()}")

    for line in actions:
        log_action(line)
    return actions


# Accent color → choose-from-preset helper
ACCENT_BY_PRESET = {
    "hashbang": "#fa4d56",
    "mackes":   "#d4a060",
    "daylight": "#f1c21b",
    "vanilla":  "#0f62fe",
    "node":     "#fa4d56",   # node is headless; accent unused
}


def configure_from_preset(preset_name: str, *, wallpaper: Optional[Path] = None) -> list[str]:
    """Convenience wrapper used by presets.apply_appearance."""
    accent = ACCENT_BY_PRESET.get(preset_name, "#fa4d56")
    return configure_greeter(accent_color=accent, wallpaper=wallpaper)


__all__ = [
    "GREETER_CONF", "GREETER_DROPIN", "STANDARD_WALLPAPER",
    "configure_greeter", "configure_from_preset", "ACCENT_BY_PRESET",
]
