#!/usr/bin/env bash
# configure-lightdm.sh — set the LightDM greeter config for a Mackes preset.
#
# Usage:
#   install-helpers/configure-lightdm.sh <preset-name>
#
# Writes /etc/lightdm/lightdm-gtk-greeter.conf and a /etc/lightdm/lightdm.conf.d/
# drop-in. Idempotent — re-running with the same preset is a no-op.
#
# Called by mackes.presets at preset-apply time via pkexec, and exposed
# as a standalone script for admins.

set -euo pipefail

PRESET="${1:-hashbang}"

declare -A ACCENT=(
    [hashbang]="#fa4d56"
    [mackes]="#d4a060"
    [daylight]="#f1c21b"
    [vanilla]="#0f62fe"
    [node]="#fa4d56"
)
ACCENT_HEX="${ACCENT[$PRESET]:-#fa4d56}"

WALLPAPER="/usr/share/mde/branding/standard-wallpaper.png"
# v4.0.2 (2026-05-23) — switched from third-party Orchis-Dark to
# the in-house Mackes-Dark theme so the LightDM greeter renders
# with the same Carbon palette + indigo accent the in-session
# top bar uses. The theme ships at
# /usr/share/themes/Mackes-Dark via the spec install step (added
# in v4.0.2). If Mackes-Dark isn't installed (older RPMs, manual
# overrides), lightdm-gtk-greeter falls back to its compile-time
# default theme — the greeter still boots, just without the
# brand stripe.
GTK_THEME="Mackes-Dark"
# v4.0.1 Q36: lock requires Carbon glyphs on the greeter for visual
# continuity with the desktop. Mackes-Carbon is the icon set the
# Workbench + panel use; pinning it here means the LightDM
# indicators (clock / session / language / a11y / power) render in
# the same Carbon line-weight style. Was Black-Sun (a third-party
# icon set) before this commit.
ICON_THEME="Mackes-Carbon"
FONT="Red Hat Text 11"

CONF_DIR="/etc/lightdm"
GREETER_CONF="${CONF_DIR}/lightdm-gtk-greeter.conf"
DROPIN_DIR="${CONF_DIR}/lightdm.conf.d"
DROPIN="${DROPIN_DIR}/50-mackes.conf"

install -d "$DROPIN_DIR"

cat > "$GREETER_CONF" <<EOF
# Generated by Mackes Shell (preset=$PRESET, accent=$ACCENT_HEX)
[greeter]
background = $WALLPAPER
theme-name = $GTK_THEME
icon-theme-name = $ICON_THEME
font-name = $FONT
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
cursor-theme-name = Adwaita
cursor-theme-size = 24
indicators = ~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format = %a %b %d, %H:%M
position = 50%,center 50%,center
panel-position = bottom
EOF

cat > "$DROPIN" <<EOF
[Seat:*]
greeter-session=lightdm-gtk-greeter
# CB-2.3 — default newly-created user accounts to the MDE Wayland
# session. Existing users keep whatever they picked last time
# (~/.dmrc per-user state wins).
user-session=mde
EOF

echo "configured LightDM greeter for preset '$PRESET' (accent $ACCENT_HEX)"
