Name:           mackes-shell
Version:        0.2.0
Release:        1%{?dist}
Summary:        Mackes Shell — XFCE control panel and shell manager for Fedora

License:        GPL-3.0
URL:            https://github.com/matthewmackes/MAP2-RELEASES
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

# Pure-Python package; no compilation, no %%py3_build needed. We only need
# python3 to know where site-packages lives.
BuildRequires:  python3

# Runtime deps the entry point and all panels need
Requires:       python3
Requires:       python3-gobject
Requires:       gtk3
Requires:       python3-pyyaml
Requires:       xfconf
Requires:       xfce4-settings
Requires:       xfce4-session

# Shell stack
Requires:       polybar
Requires:       plank
Requires:       rofi

# Network / firewall / audio
Requires:       NetworkManager
Recommends:     firewalld
Recommends:     pulseaudio-utils

# Theme / icon / font defaults referenced by shipped presets
Recommends:     papirus-icon-theme
Recommends:     arc-theme
Recommends:     google-droid-sans-fonts
Recommends:     jetbrains-mono-fonts

# Notifications daemon that replaces xfce4-notifyd in the chupre preset (X1)
Recommends:     dunst

# QNM is detected at runtime; soft dep so users without QNM still get
# Network → QNM panel with an install prompt (C2/Q38 lock).
Recommends:     qnm

# Force /usr as the base so the package lands in /usr/lib/python3.X/site-packages
# (the Fedora convention for distro-installed Python packages), not /usr/local.
%global py3_ver %(python3 -c "import sys; print('%d.%d' % sys.version_info[:2])")
%global py3_sitelib /usr/lib/python%{py3_ver}/site-packages

%description
Mackes Shell is the single GTK control panel that replaces xfce4-settings
as the daily interface for managing an XFCE-based Fedora workstation. It
absorbs the Polybar / Plank / Rofi shell stack into one window with a
dashboard, six task tabs (Look & Feel, Shell, Devices, Network, System,
Maintain) and a first-run wizard that brings a fresh machine to a known
preset in under five minutes.

%prep
# sdist generated by `python -m build` unpacks to mackes_shell-<version>/
# (PyPI canonical underscore name), not mackes-shell-<version>/.
%autosetup -n mackes_shell-%{version}

%build
# Pure Python — nothing to compile.

%install
# 1. Install the Python package directly into site-packages. Skip
#    setuptools/pip entirely — Mackes has no C extensions and no
#    generated metadata that matters at runtime.
install -d %{buildroot}%{py3_sitelib}
cp -r mackes %{buildroot}%{py3_sitelib}/

# 2. dist-info so dnf/rpm-py-inspector and `pip list` can see it
install -d %{buildroot}%{py3_sitelib}/mackes_shell-%{version}.dist-info
cat > %{buildroot}%{py3_sitelib}/mackes_shell-%{version}.dist-info/METADATA <<EOF
Metadata-Version: 2.1
Name: mackes-shell
Version: %{version}
Summary: %{summary}
License: %{license}
EOF
cat > %{buildroot}%{py3_sitelib}/mackes_shell-%{version}.dist-info/INSTALLER <<EOF
rpm
EOF

# 3. Shipped read-only data
install -d %{buildroot}%{_datadir}/%{name}/data
cp -r data/presets        %{buildroot}%{_datadir}/%{name}/data/
cp -r data/shell-profiles %{buildroot}%{_datadir}/%{name}/data/  # includes upstream/ adi1090x themes
cp -r data/plank-themes   %{buildroot}%{_datadir}/%{name}/data/
cp -r data/wallpapers     %{buildroot}%{_datadir}/%{name}/data/
cp -r data/css            %{buildroot}%{_datadir}/%{name}/data/
cp -r data/dnf            %{buildroot}%{_datadir}/%{name}/data/
cp -r data/systemd        %{buildroot}%{_datadir}/%{name}/data/
cp -r data/grub           %{buildroot}%{_datadir}/%{name}/data/

# 3a. MAP2 branding — logo placed on About, Wizard welcome, Dashboard header
install -d %{buildroot}%{_datadir}/%{name}/branding
cp -r branding/* %{buildroot}%{_datadir}/%{name}/branding/

# 4. Install helper scripts (called from %%post / %%preun)
install -d %{buildroot}%{_datadir}/%{name}/install-helpers
install -m 0755 install-helpers/hide-xfce-settings.sh \
    %{buildroot}%{_datadir}/%{name}/install-helpers/
install -m 0755 install-helpers/restore-xfce-settings.sh \
    %{buildroot}%{_datadir}/%{name}/install-helpers/
install -m 0755 install-helpers/add-mackes-repo.sh \
    %{buildroot}%{_datadir}/%{name}/install-helpers/
install -m 0755 install-helpers/install-recovery.sh \
    %{buildroot}%{_datadir}/%{name}/install-helpers/

# 5. Top-level launcher and icon
install -D -m 0644 data/applications/mackes-shell.desktop \
    %{buildroot}%{_datadir}/applications/mackes-shell.desktop
install -D -m 0644 data/icons/mackes-shell.svg \
    %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/mackes-shell.svg

# 6. /usr/bin/mackes wrapper (same as the wheel's console_script)
install -d %{buildroot}%{_bindir}
cat > %{buildroot}%{_bindir}/mackes <<'EOF'
#!/usr/bin/env bash
exec python3 -m mackes "$@"
EOF
chmod 0755 %{buildroot}%{_bindir}/mackes

%post
/usr/share/%{name}/install-helpers/hide-xfce-settings.sh || :

%preun
# Only on uninstall, not upgrade ($1 == 0 → final removal)
if [ "$1" = "0" ]; then
    /usr/share/%{name}/install-helpers/restore-xfce-settings.sh || :
fi

%files
%license LICENSE
%doc README.md CHANGELOG.md docs/MACKES_SHELL_SPEC.md docs/MIGRATION_FROM_V2.2.md
%{_bindir}/mackes
%{py3_sitelib}/mackes/
%{py3_sitelib}/mackes_shell-%{version}.dist-info/
%{_datadir}/%{name}/
%{_datadir}/applications/mackes-shell.desktop
%{_datadir}/icons/hicolor/scalable/apps/mackes-shell.svg

%changelog
* Sat May 16 2026 Matt Mackes <matthewmackes@gmail.com> - 0.2.0-1
- Identity: stripped "PRIVATE WORK / Sub Testing Release" markers from
  dashboard, wizard, and About dialog.
- Wizard rebuilt as a 3-act ceremony: spare welcome, 4-card preset picker
  with wallpaper thumbnails, narrated apply ("Becoming <preset>" →
  "You are now <preset>").
- Replaced single chupre preset with FOUR: hashbang (default, display
  '#!'), mackes, daylight, vanilla. Each ships its own polybar / plank /
  rofi profile + wallpaper.
- Design system: SF Pro typography stack, mackes-* CSS classes, and
  per-preset accent CSS swapped at startup based on state.active_preset.
- New Polybar Editor (replaces Q12 preset-picker lock): 21 vendored
  adi1090x families, pure-function generator, 3-zone DnD module editor,
  save-as-profile, live debounced apply.
- MaintenanceKit: 4 new panels — System Update (pkexec dnf wrapper),
  Drift (first-class per-key revert/adopt), Fonts (fc-list browser +
  preview + quick installs), Power (power-profiles-daemon), Resources
  (CPU/RAM/disk live cards).
- Recovery shell foundation: mackes/recover.py TTY snapshot picker,
  mackes-recovery.target systemd unit, GRUB submenu source, idempotent
  install-helpers/install-recovery.sh.
- Update mechanism plumbing: data/dnf/mackes-shell.repo pointing at
  matthewmackes.github.io/MAP2-RELEASES, add-mackes-repo.sh helper.
- ISO build scaffolding: packaging/iso/mackes-xfce.ks kickstart + `make
  iso` target.
- Headless apply CLI: `python3 -m mackes.cli_apply --preset NAME`.
- Test runner that works without pytest: tests/_run_without_pytest.py
  (`make test-nodeps`).
- Vendored adi1090x/polybar-themes (GPL-3.0) under
  data/shell-profiles/polybar/upstream/ — 8.7 MB, 21 families.

* Sat May 16 2026 Matt Mackes <matthewmackes@gmail.com> - 0.1.1-1
- MAP2 Sub Testing Release. PRIVATE WORK.
- Drop Workstation/Laptop/Audio Rig/Server Console presets; ship only chupre (Q1).
- Add Apps tab (Install / Remove / Installed) — curated install set with
  third-party repo auto-enablement (Microsoft Edge, VS Code) plus Cursor
  AppImage and Claude CLI via npm (C1–C3).
- Add Lean XFCE removal — xfce4-panel/appfinder/xfdesktop/xfce4-notifyd
  removed when their replacements (polybar/rofi/plank/dunst) are running.
  Reinstalled automatically on uninstall (X1–X5).
- Add Maintain → Uninstall + mackes --uninstall CLI + uninstall.sh artifact.
  Auto-snapshots to ~/Desktop/, wipes user files, resets xfconf, cleans v2.2
  leftovers (Q8–Q30, Q46–Q47).
- Add session-manager extension: managed-process supervisor with status
  dots on Dashboard + Start/Stop/Restart controls in System → Session
  (C6, C11). Also drives chupre dotfiles staging (alacritty + gtk-3.0 +
  gtk-4.0 from chupre/dotfiles tree/v2/.config).
- Fix Polybar autostart: install ~/.config/autostart/mackes-polybar.desktop,
  parse bar names from the active profile (no more hardcoded `polybar
  mackes`), and capture stderr to ~/.local/share/mackes-shell/logs/polybar.log
  (P1 lock).
- Wire MAP2 branding logo into About dialog, Wizard welcome screen and
  Dashboard header. Add 'PRIVATE WORK — Sub Testing Release' banner to
  the Dashboard.

* Fri May 15 2026 Matt Mackes <matthewmackes@gmail.com> - 0.1.0-1
- Initial Mackes Shell RPM.
- Replaces xfce4-settings menu entries via NoDisplay overrides (Q19).
- Ships the erikdubois/plankthemes catalog under data/plank-themes/.
- Single-binary entry: /usr/bin/mackes routes to wizard or workbench.
