#!/usr/bin/env bash
# configure-lightdm.sh — set the LightDM greeter config for a Mackes preset.
#
# Usage:
#   install-helpers/configure-lightdm.sh <preset-name>
#
# Writes /etc/lightdm/lightdm-gtk-greeter.conf and a /etc/lightdm/lightdm.conf.d/
# drop-in. Idempotent — re-running with the same preset is a no-op.
#
# Called by mackes.presets at preset-apply time via pkexec, and exposed
# as a standalone script for admins.

set -euo pipefail

PRESET="${1:-hashbang}"

declare -A ACCENT=(
    [hashbang]="#fa4d56"
    [mackes]="#d4a060"
    [daylight]="#f1c21b"
    [vanilla]="#0f62fe"
    [node]="#fa4d56"
)
ACCENT_HEX="${ACCENT[$PRESET]:-#fa4d56}"

WALLPAPER="/usr/share/mackes-shell/branding/standard-wallpaper.png"
GTK_THEME="Orchis-Dark"
ICON_THEME="Black-Sun"
FONT="Red Hat Text 11"

CONF_DIR="/etc/lightdm"
GREETER_CONF="${CONF_DIR}/lightdm-gtk-greeter.conf"
DROPIN_DIR="${CONF_DIR}/lightdm.conf.d"
DROPIN="${DROPIN_DIR}/50-mackes.conf"

install -d "$DROPIN_DIR"

cat > "$GREETER_CONF" <<EOF
# Generated by Mackes Shell (preset=$PRESET, accent=$ACCENT_HEX)
[greeter]
background = $WALLPAPER
theme-name = $GTK_THEME
icon-theme-name = $ICON_THEME
font-name = $FONT
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
cursor-theme-name = Adwaita
cursor-theme-size = 24
indicators = ~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format = %a %b %d, %H:%M
position = 50%,center 50%,center
panel-position = bottom
EOF

cat > "$DROPIN" <<EOF
[Seat:*]
greeter-session=lightdm-gtk-greeter
EOF

echo "configured LightDM greeter for preset '$PRESET' (accent $ACCENT_HEX)"
