"""§8.13 Layer 3 — Caddy reverse proxy + private CA management.

Mackes installs Caddy on every peer and configures it to expose every
mesh peer's HTTP services under https://media.mesh/<service>/<peer>/.
TLS via a Mackes-managed private CA whose root is distributed via the
mesh-sync `ca-root` bucket.

Layered on top of the live mesh-services registry — the Caddyfile is
regenerated whenever the registry changes.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Iterable

from mackes.logging import log_action
from mackes.mesh_services import ServiceHit, load_catalog, load_registry
from mackes.state import DATA_DIR


CADDYFILE      = Path("/etc/caddy/Caddyfile.mesh")
CADDYFILE_MAIN = Path("/etc/caddy/Caddyfile")
MESH_CA_DIR    = Path("/var/lib/mackes/ca")
MESH_CA_CERT   = MESH_CA_DIR / "mesh-ca.crt"
MESH_CA_KEY    = MESH_CA_DIR / "mesh-ca.key"

_HAVE = shutil.which


def _pkexec(cmd: list[str], *, input_text: str = "", timeout: int = 30) -> tuple[int, str, str]:
    prefix = ["pkexec"] if _HAVE("pkexec") else (["sudo"] if _HAVE("sudo") else [])
    try:
        proc = subprocess.run(
            prefix + cmd,
            input=input_text if input_text else None,
            capture_output=True, text=True, timeout=timeout,
        )
        return proc.returncode, proc.stdout or "", proc.stderr or ""
    except (OSError, subprocess.TimeoutExpired) as e:
        return 1, "", str(e)


# ---------------------------------------------------------------------------
# Caddyfile generation
# ---------------------------------------------------------------------------


def generate_caddyfile(hits: Iterable[ServiceHit]) -> str:
    """Emit a Caddyfile fragment routing https://media.mesh/<svc>/<peer>/."""
    lines = [
        "# Generated by mackes.caddy_gateway — do not edit by hand.",
        "# Regenerated whenever the mesh-services registry changes.",
        "",
        "{",
        "    auto_https off",
        "    pki {",
        "        ca mackes-mesh-ca {",
        f"            root_cn \"Mackes Mesh CA\"",
        "        }",
        "    }",
        "}",
        "",
        "https://media.mesh {",
        "    tls internal",
        "    encode gzip",
        "    log {",
        "        output file /var/log/caddy/media.mesh.log",
        "    }",
    ]
    catalog = {d.name: d for d in load_catalog()}
    hits = list(hits)
    if not hits:
        lines.append("    # (no services discovered yet)")
    for hit in hits:
        # Path: /<service>/<peer>/ → http://<peer>.mesh:<port>/
        svc_disp = catalog.get(hit.service).display if hit.service in catalog else hit.service
        target_host = f"{hit.peer}.mesh:{hit.port}"
        slug = f"/{hit.service}/{hit.peer}"
        lines.extend([
            "",
            f"    # {svc_disp} on {hit.peer}",
            f"    handle_path {slug}/* {{",
            f"        rewrite * /{{path}}",
            f"        reverse_proxy {hit.scheme}://{target_host}",
            f"    }}",
        ])

    # ---- Remote desktop (v1.2.0 birthright) ---------------------------
    # /desktop/ → local Tomcat-hosted Guacamole web app
    lines.extend([
        "",
        "    # Remote desktop — local Guacamole web app",
        "    handle_path /desktop/* {",
        "        reverse_proxy http://127.0.0.1:8080/guacamole/",
        "    }",
    ])

    # Catch-all index page (lists discovered services)
    lines.extend([
        "",
        "    handle / {",
        "        respond \"Mackes Mesh Gateway — see /index.html for service list\" 200",
        "    }",
        "",
        "    handle_errors {",
        "        respond \"upstream {http.error.status_code}\" {http.error.status_code}",
        "    }",
        "}",
    ])
    return "\n".join(lines) + "\n"


def write_caddyfile() -> list[str]:
    body = generate_caddyfile(load_registry())
    rc, out, err = _pkexec(["tee", str(CADDYFILE)], input_text=body)
    if rc != 0:
        return [f"could not write {CADDYFILE}: {err.strip()}"]
    return [f"wrote {CADDYFILE} ({len(body.splitlines())} lines)"]


# ---------------------------------------------------------------------------
# Lifecycle
# ---------------------------------------------------------------------------


def is_caddy_running() -> bool:
    rc, out, _ = _pkexec(["systemctl", "is-active", "caddy"], timeout=5)
    return rc == 0 and out.strip() == "active"


def enable_gateway() -> list[str]:
    actions: list[str] = []
    if not _HAVE("caddy"):
        actions.append("caddy binary missing — install with: sudo dnf install caddy")
        return actions
    actions.extend(write_caddyfile())
    # Append an import line to the main Caddyfile if not present
    import_line = f"import {CADDYFILE}"
    if CADDYFILE_MAIN.exists():
        try:
            current = CADDYFILE_MAIN.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if import_line not in current:
            rc, _, err = _pkexec(
                ["bash", "-c", f"echo '{import_line}' >> {CADDYFILE_MAIN}"],
                timeout=5,
            )
            actions.append(
                f"appended import to {CADDYFILE_MAIN}: rc={rc} {err.strip()}"
            )
    else:
        actions.append(f"{CADDYFILE_MAIN} missing; not auto-importing")
    rc, out, err = _pkexec(["systemctl", "enable", "--now", "caddy.service"], timeout=30)
    actions.append(f"systemctl enable --now caddy rc={rc} {(err or out).strip().splitlines()[-1] if (err+out).strip() else ''}")
    for line in actions:
        log_action(line)
    return actions


def disable_gateway() -> list[str]:
    rc, _, err = _pkexec(["systemctl", "disable", "--now", "caddy.service"], timeout=15)
    return [f"systemctl disable --now caddy rc={rc} {err.strip()}"]


def reload_gateway() -> list[str]:
    """Re-render Caddyfile.mesh and ask Caddy to reload."""
    actions = write_caddyfile()
    rc, _, err = _pkexec(["systemctl", "reload", "caddy.service"], timeout=10)
    actions.append(f"systemctl reload caddy rc={rc} {err.strip()}")
    return actions


# ---------------------------------------------------------------------------
# Private CA distribution
# ---------------------------------------------------------------------------


def install_ca_into_trust_store() -> list[str]:
    """Copy Caddy's internal CA root into the system trust store."""
    actions: list[str] = []
    # Caddy stores its internal CA at /var/lib/caddy/.local/share/caddy/pki/
    candidates = [
        Path("/var/lib/caddy/.local/share/caddy/pki/authorities/local/root.crt"),
        Path("/etc/caddy/pki/authorities/local/root.crt"),
        MESH_CA_CERT,
    ]
    src = next((c for c in candidates if c.exists()), None)
    if src is None:
        return ["Caddy CA root not found yet — start the gateway first"]
    dest = Path("/etc/pki/ca-trust/source/anchors/mackes-mesh-ca.crt")
    rc, _, err = _pkexec(["install", "-m", "0644", str(src), str(dest)], timeout=5)
    if rc != 0:
        return [f"could not install CA cert: {err.strip()}"]
    actions.append(f"installed {src.name} -> {dest}")
    rc2, _, err2 = _pkexec(["update-ca-trust", "extract"], timeout=15)
    actions.append(f"update-ca-trust rc={rc2} {err2.strip()}")
    for line in actions:
        log_action(line)
    return actions


__all__ = [
    "CADDYFILE", "CADDYFILE_MAIN",
    "generate_caddyfile", "write_caddyfile",
    "enable_gateway", "disable_gateway", "reload_gateway",
    "is_caddy_running", "install_ca_into_trust_store",
]
