"""i3 gaps profiles — 5 named configurations the user can pick from
the Workbench → System → Window Manager panel.

User lock 2026-05-19: ship 5 popular i3 gaps configurations as
selectable profiles. The picker writes the chosen profile to
`~/.config/i3/config.d/mackes-gaps.conf`, which the user's i3 config
includes via a single `include ~/.config/i3/config.d/*.conf` line.
The applied profile takes effect immediately via `i3-msg reload`.

The 5 profiles span the spectrum from compact (no gaps, max content
density) to centered focus (large outer gaps that pad short laptop
screens into a phone-like reading column). Profile names + numbers
match the most-recommended r/i3wm + r/unixporn configurations as of
2026.
"""
from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import List


@dataclass(frozen=True)
class GapsProfile:
    """One named i3 gaps configuration.

    `inner` is the gap between tiled siblings; `outer` is the gap
    between the outermost windows and the screen edges (added on top
    of `inner` per i3 semantics). `smart_gaps` collapses gaps when
    only one window is on a workspace; `smart_borders` does the same
    for borders. Both are i3-gaps defaults the profiles toggle.
    """
    key: str
    label: str
    description: str
    inner: int
    outer: int
    smart_gaps: bool
    smart_borders: bool


# Five popular i3 gaps configurations — ordered from compact (1) to
# spacious (5). The default Mackes config ships at "subtle" (matches
# data/i3/config — `gaps inner 4` + `gaps outer 0`).
PROFILES: List[GapsProfile] = [
    GapsProfile(
        key="none",
        label="No Gaps",
        description="No spacing between windows. Maximum content density — "
                    "tiles touch each other and the screen edges.",
        inner=0,
        outer=0,
        smart_gaps=False,
        smart_borders=False,
    ),
    GapsProfile(
        key="subtle",
        label="Subtle (Mackes default)",
        description="4 px inner, no outer. Just enough separation to "
                    "tell tiles apart. The Mackes default — what the "
                    "stock data/i3/config ships.",
        inner=4,
        outer=0,
        smart_gaps=True,
        smart_borders=True,
    ),
    GapsProfile(
        key="comfortable",
        label="Comfortable",
        description="10 px inner, 5 px outer. Generous whitespace without "
                    "wasting screen real estate. Popular r/unixporn baseline.",
        inner=10,
        outer=5,
        smart_gaps=True,
        smart_borders=True,
    ),
    GapsProfile(
        key="spacious",
        label="Spacious",
        description="16 px inner, 8 px outer. Showcase-grade gaps that "
                    "make each window feel like its own card.",
        inner=16,
        outer=8,
        smart_gaps=True,
        smart_borders=True,
    ),
    GapsProfile(
        key="centered",
        label="Centered Focus",
        description="20 px inner, 40 px outer. Big outer gaps pad short "
                    "laptop screens into a phone-like reading column — "
                    "ideal for writing or single-window focus modes.",
        inner=20,
        outer=40,
        smart_gaps=True,
        smart_borders=True,
    ),
]


def get_profile(key: str) -> GapsProfile | None:
    """Look up a profile by key. Returns `None` for unknown keys."""
    for p in PROFILES:
        if p.key == key:
            return p
    return None


def render_profile(profile: GapsProfile) -> str:
    """Render the i3 config fragment for `profile`.

    Output is a complete i3 config snippet the user can drop into
    `~/.config/i3/config.d/mackes-gaps.conf`; the shipped
    `data/i3/config` includes this directory via
    `include ~/.config/i3/config.d/*.conf` (added 1.1.0).
    """
    smart_gaps = "on" if profile.smart_gaps else "off"
    smart_borders = "on" if profile.smart_borders else "off"
    return (
        f"# Mackes Shell — i3 gaps profile: {profile.label}\n"
        f"# Generated by mackes.i3_gaps.apply_profile().\n"
        f"# Edit Workbench → System → Window Manager to change profile.\n"
        f"\n"
        f"gaps inner {profile.inner}\n"
        f"gaps outer {profile.outer}\n"
        f"smart_gaps {smart_gaps}\n"
        f"smart_borders {smart_borders}\n"
    )


def config_d_path() -> Path:
    """Return `~/.config/i3/config.d/mackes-gaps.conf`."""
    home = Path(os.path.expanduser("~"))
    return home / ".config" / "i3" / "config.d" / "mackes-gaps.conf"


def apply_profile(key: str) -> List[str]:
    """Write the profile to disk + reload i3.

    Returns a list of human-readable action lines describing what
    happened (for the panel's status row). Idempotent — re-applying
    the same profile rewrites the file with identical content + runs
    one reload.
    """
    actions: List[str] = []
    profile = get_profile(key)
    if profile is None:
        actions.append(f"i3-gaps: unknown profile {key!r}")
        return actions

    target = config_d_path()
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render_profile(profile), encoding="utf-8")
        actions.append(f"i3-gaps: wrote {target} ({profile.label})")
    except OSError as e:
        actions.append(f"i3-gaps: write failed: {e}")
        return actions

    if shutil.which("i3-msg"):
        try:
            subprocess.run(
                ["i3-msg", "reload"],
                capture_output=True, timeout=5, check=False,
            )
            actions.append("i3-gaps: reloaded i3")
        except (OSError, subprocess.TimeoutExpired) as e:
            actions.append(f"i3-gaps: i3-msg reload failed: {e}")
    else:
        actions.append("i3-gaps: i3-msg missing — restart i3 to apply")

    return actions


def detect_current() -> str | None:
    """Return the key of the currently-applied profile (best-effort).

    Reads `~/.config/i3/config.d/mackes-gaps.conf` if it exists and
    matches any of the shipped profiles' rendered output. Returns
    `None` when no Mackes-shipped profile is detected (user-edited or
    unset).
    """
    target = config_d_path()
    if not target.is_file():
        return None
    try:
        text = target.read_text(encoding="utf-8")
    except OSError:
        return None
    for p in PROFILES:
        if render_profile(p).strip() == text.strip():
            return p.key
    return None
