"""Polybar config generator — pure function from (theme, options) -> ini text.

Stitches a self-contained polybar config from one of the vendored families:

  1. Family's `colors.ini` (palette)
  2. Family's `modules.ini` + `user_modules.ini` (module definitions)
  3. Family's `bars.ini` (bar style helpers — included for backwards-compat
     so themes like `forest` that reference [bar] glyphs still resolve)
  4. A generated `[bar/mackes]` section using the chosen layout + geometry

The output is a single .ini that polybar can load with no `include-file`
directives, so callers don't have to copy any other files alongside it.

This module does no I/O against ~/.config/polybar/ — that's the caller's job.
Run via `python -m mackes.polybar_gen --theme forest` for a dump to stdout.
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from typing import Sequence

from mackes import polybar_catalog as cat


# ---------------------------------------------------------------------------
# Generator options
# ---------------------------------------------------------------------------


@dataclass
class GenOptions:
    family_key: str               # e.g. "simple/forest" or just "forest"
    position: str = "top"         # "top" | "bottom"
    height: int = 32
    width: str = "100%"
    radius: int = 0
    monitor: str = ""             # empty = polybar picks
    font_scale: float = 1.0       # multiplier on family-provided fonts (post-gen)
    modules_left: Sequence[str] = field(default_factory=tuple)
    modules_center: Sequence[str] = field(default_factory=tuple)
    modules_right: Sequence[str] = field(default_factory=tuple)
    use_family_layout: bool = True  # if True, ignore the modules-* fields and
                                    # use the family's bar_layout as the default


# ---------------------------------------------------------------------------
# File slurp helpers (vendored INI files include header banners + comments
# we want to keep as-is; cheaper to inline than re-format)
# ---------------------------------------------------------------------------


def _slurp(path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate(opts: GenOptions) -> str:
    """Return a self-contained polybar config.ini string."""
    fam = cat.get_family(opts.family_key)
    if fam is None:
        raise ValueError(f"unknown family: {opts.family_key!r}")

    if opts.use_family_layout:
        layout = cat.bar_layout(fam)
        ml, mc, mr = layout.modules_left, layout.modules_center, layout.modules_right
    else:
        ml = tuple(opts.modules_left)
        mc = tuple(opts.modules_center)
        mr = tuple(opts.modules_right)

    bottom = "true" if opts.position == "bottom" else "false"

    parts: list[str] = []
    parts.append(f";; Generated by mackes.polybar_gen from family {fam.key!r}.\n")
    parts.append(f";; To regenerate: python -m mackes.polybar_gen --theme {fam.key}\n\n")
    parts.append(_slurp(fam.path / "colors.ini").rstrip() + "\n\n")
    parts.append(_slurp(fam.path / "bars.ini").rstrip() + "\n\n")
    parts.append(_slurp(fam.path / "modules.ini").rstrip() + "\n\n")
    parts.append(_slurp(fam.path / "user_modules.ini").rstrip() + "\n\n")

    bar = [
        "[bar/mackes]",
        f"monitor = {opts.monitor}",
        f"width = {opts.width}",
        f"height = {opts.height}",
        f"radius = {opts.radius}",
        f"bottom = {bottom}",
        "fixed-center = true",
        "background = ${color.background}",
        "foreground = ${color.foreground}",
        "line-size = 2",
        "border-size = 0",
        f"modules-left = {' '.join(ml)}",
        f"modules-center = {' '.join(mc)}",
        f"modules-right = {' '.join(mr)}",
        "wm-restack = generic",
        "cursor-click = pointer",
        "",
    ]
    parts.append("\n".join(bar))
    return "".join(parts)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(
        prog="python -m mackes.polybar_gen",
        description="Generate a polybar config.ini from a vendored theme family.",
    )
    p.add_argument("--theme", required=True,
                   help="family key, e.g. 'forest' or 'simple/forest'")
    p.add_argument("--position", choices=("top", "bottom"), default="top")
    p.add_argument("--height", type=int, default=32)
    p.add_argument("--width", default="100%")
    p.add_argument("--radius", type=int, default=0)
    p.add_argument("--monitor", default="")
    p.add_argument("--modules-left", nargs="*", default=None)
    p.add_argument("--modules-center", nargs="*", default=None)
    p.add_argument("--modules-right", nargs="*", default=None)
    p.add_argument("--list", action="store_true",
                   help="list available family keys and exit")
    args = p.parse_args(argv)

    if args.list:
        for f in cat.list_families():
            print(f.key)
        return 0

    use_family = (args.modules_left is None
                  and args.modules_center is None
                  and args.modules_right is None)
    opts = GenOptions(
        family_key=args.theme,
        position=args.position,
        height=args.height,
        width=args.width,
        radius=args.radius,
        monitor=args.monitor,
        modules_left=tuple(args.modules_left or ()),
        modules_center=tuple(args.modules_center or ()),
        modules_right=tuple(args.modules_right or ()),
        use_family_layout=use_family,
    )
    try:
        print(generate(opts))
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(_main(sys.argv[1:]))
